name: safedest_driver
description: 'Safedest Driver'
publish_to: 'none'

version: 1.0.4

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0

  # HTTP & API
  http: ^1.1.0
  dio: ^5.3.2
  lottie: ^3.0.0

  # State Management
  provider: ^6.1.1 # Will be removed after migration
  get: ^4.6.6 # GetX for state management & navigation

  # Local Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  sqflite: ^2.3.0
  path: ^1.8.3

  # Location & Maps
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  google_maps_flutter: ^2.5.0

  # Push Notifications
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^17.2.3

  # Utils
  intl: 0.20.2
  url_launcher: ^6.2.1
  image_picker: ^1.0.4
  file_picker: ^8.0.0
  flutter_tts: ^3.8.3
  cached_network_image: ^3.3.0
  open_file: ^3.3.2

  # UI Components
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  pull_to_refresh: ^2.0.0
  fl_chart: ^0.64.0
  tutorial_coach_mark: ^1.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/flags/

  fonts:
    - family: saudi_riyal
      fonts:
        - asset: assets/fonts/saudi_riyal.ttf
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Black.ttf
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/tajawal/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
